"""Initial migration.

Revision ID: 1ccbea945de2
Revises: ecc80bae75af
Create Date: 2023-05-02 15:42:29.168680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ccbea945de2'
down_revision = 'ecc80bae75af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('user')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('gender')
        batch_op.drop_index('phone')

    op.drop_table('employee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=220), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=400), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=400), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=400), nullable=False),
    sa.Column('phone', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('salary', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index('phone', ['phone'], unique=False)
        batch_op.create_index('gender', ['gender'], unique=False)
        batch_op.create_index('email', ['email'], unique=False)

    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=220), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=False)

    # ### end Alembic commands ###
