"""Initial migration.

Revision ID: 5f3db090081f
Revises: 4a915d9e865a
Create Date: 2023-05-02 16:52:58.589103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3db090081f'
down_revision = '4a915d9e865a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index('gender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index('gender', ['gender'], unique=False)

    # ### end Alembic commands ###
