"""Initial migration.

Revision ID: ecc80bae75af
Revises: 559196947ea8
Create Date: 2023-05-02 14:22:05.748708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ecc80bae75af'
down_revision = '559196947ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=220), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=400), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('username')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
